language: node_js
before_script:
  - sleep 15
node_js:
  - "0.11"
  - "0.10"
services:
  - mongodb
env:
  - secure: HIEQz1/A8OfHhxKGOVA/5lIzTS4Eg4DVv8qBwq7hGzLj3xjuo/7alxlkj4JrE4zCsi2R7TSWWPbtK+8cKGrOuI/lwLpVfuBKACvJeLTlzW4nmDmJznXVIV0pdZC96dgEKpXvZjop9s3Sl2fgFcymmysK+O6lJsQe3KM5Prn55Og=
after_success: npm run codeclimate
